# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exec_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=1000, null=True)),
                ('violence', models.CharField(max_length=200, null=True)),
                ('adult', models.CharField(max_length=200, null=True)),
                ('spoof', models.CharField(max_length=200, null=True)),
                ('medical', models.CharField(max_length=200, null=True)),
                ('page_title', models.CharField(max_length=1000, null=True)),
                ('page_url', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
