# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageassessment',
            name='crawl',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crawl.Crawl'),
        ),
    ]
